- name: Consul | Install Packages
  ansible.builtin.apt: 
    name: "{{ consul_packages }}"
    state: latest
    update_cache: true

- name: Consul | Add user
  ansible.builtin.user:
    name: "consul"
    shell: "/bin/false"
    system: false
    create_home: false
      #    append: true
      #    groups:
      #    - www-data

- name: Consul | Copy consul binaries
  ansible.builtin.copy:
    src: "binaries/consul_1.17.0_linux_amd64.zip"
    dest: "/tmp/consul_1.17.0_linux_amd64.zip"

- name: Consul | Unarchive consul binaries
  ansible.builtin.unarchive:
    src: "/tmp/consul_1.17.0_linux_amd64.zip"
    dest: "/usr/local/sbin"
    remote_src: true

- name: Consul | Make directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  loop:
  - /etc/consul.d
  - "{{ consul_data_dir }}"

- name: Consul | Configure
  ansible.builtin.template:
    src: "templates/consul-client.hcl.j2"
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
  notify: reload consul

- name: Consul | Configure Services
  ansible.builtin.template:
    src: "templates/consul-service-app.hcl.j2"
    dest: "/etc/consul.d/services.hcl"
    owner: consul
    group: consul
  notify: reload consul

- name: Consul | Copy systemd units
  ansible.builtin.copy:
    src: "files/consul.service"  
    dest: "/etc/systemd/system/consul.service"

- name: Consul | Check if consul is running
  ansible.builtin.systemd:
    name: consul
    state: started
    daemon_reload: true

