- name: Database | Install packages
  ansible.builtin.apt:
    name: "{{ db_packages }}"
    state: latest
    update_cache: true

- name: Database | Install pymysql via pip
  ansible.builtin.pip:
    name: pymysql
    state: latest

- name: Database | Configure listen address
  ansible.builtin.lineinfile:
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    search_string: "bind-address"
    line: "bind-address = 0.0.0.0"
  notify: 
  - restart mariadb-server

- name: Database | Create Database for Wordpress
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Database | Create database user using hashed password with all database privileges
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    host: "192.168.0.0/255.255.0.0"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  notify: 
  - restart mariadb-server
